{
  "swagger" : "2.0",
  "info" : {
    "description" : "API de integração para as funcionalidades de cartão pré-pago no marketplace e estabelecimento.",
    "version" : "0.0.2",
    "title" : "Cartão Pré-pago"
  },
  "host": "api.zoop.ws",
  "basePath" : "/v1",
  "tags" : [ {
    "name" : "Cards",
    "description" : "Operações de cartão pré-pago pelo marketplace"
  }, {
    "name" : "Manager",
    "description" : "Operações de cartão pré-pago pelo estabelecimento"
  } ],
  "schemes" : [ "https", "http" ],
  "security" : [ {
    "ApiKeyAuth" : [ ]
  } ],
  "paths" : {
    "/marketplaces/{marketplace_id}/prepaid-cards" : {
      "get" : {
        "tags" : [ "Cards" ],
        "summary" : "Lista de cartões pré-pagos associados pelo marketplace",
        "description" : "A listagem é feita pelo market place, trazendo todos os cartões associados por ele a qualquer estabelecimento",
        "operationId" : "get_all_cards",
        "parameters" : [ {
          "name" : "marketplace_id",
          "in" : "path",
          "description" : "ID do marketplace para escopo dos cartões",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "Listagem efetuada com sucesso",
            "schema" : {
              "$ref" : "#/definitions/Cards"
            }
          },
          "401" : {
            "description" : "Solicitação não autorizada"
          }
        }
      },
      "post" : {
        "tags" : [ "Cards" ],
        "summary" : "Adicionando cartão pré-pago a um estabelecimento.",
        "description" : "Com essa operação, é possível para o marketplace, adicionar os cartões pré-pagos de sua rede aos respectivos estabelecimentos.",
        "operationId" : "associate_card",
        "parameters" : [ {
          "name" : "marketplace_id",
          "in" : "path",
          "description" : "ID do marketplace para escopo dos cartões",
          "required" : true,
          "type" : "string"
        }, {
          "in" : "body",
          "name" : "body",
          "description" : "Dados do cartão necessário para associação com o estabelecimento",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/CardAssociation"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "A adiçào foi feita com sucesso!",
            "schema" : {
              "$ref" : "#/definitions/Card"
            }
          },
          "400" : {
            "description" : "Dados informados são inválidos"
          },
          "401" : {
            "description" : "Solicitação não autorizada"
          }
        }
      },
      "delete" : {
        "tags" : [ "Cards" ],
        "summary" : "Excluir um cartão associado",
        "description" : "Exclui um cartão associado a um estabelecimento, essa ação bloqueia e desassocia o cartão para a sua devida exclusão",
        "operationId" : "delete_card_by_bank_account",
        "parameters" : [ {
          "name" : "marketplace_id",
          "in" : "path",
          "description" : "ID do marketplace para escopo dos cartões",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "bank_account_id",
          "in" : "query",
          "description" : "ID do cartão a ser excluido",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "Exclusão feita com sucesso!",
            "schema" : {
              "$ref" : "#/definitions/Card"
            }
          },
          "400" : {
            "description" : "ID informado é inválido"
          },
          "401" : {
            "description" : "Solicitação não autorizada"
          },
          "404" : {
            "description" : "Cartão não encontrado"
          }
        }
      }
    },
    "/marketplaces/{marketplace_id}/prepaid-cards/{card_id}" : {
      "get" : {
        "tags" : [ "Cards" ],
        "summary" : "Procura um cartão pelo ID",
        "description" : "Retorna um cartão associado a um estabelecimento procurando pelo ID informado",
        "operationId" : "get_card_detail",
        "parameters" : [ {
          "name" : "marketplace_id",
          "in" : "path",
          "description" : "ID do marketplace para escopo dos cartões",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "card_id",
          "in" : "path",
          "description" : "ID do cartão a ser localizado",
          "required" : true,
          "type" : "integer",
          "format" : "int64"
        } ],
        "responses" : {
          "200" : {
            "description" : "Detalhe do cartão encontrado.",
            "schema" : {
              "$ref" : "#/definitions/CardDetail"
            }
          },
          "400" : {
            "description" : "ID informado é inválido"
          },
          "401" : {
            "description" : "Solicitação não autorizada"
          },
          "404" : {
            "description" : "Cartão não encontrado"
          }
        }
      }
    },
    "/marketplaces/{marketplace_id}/sellers/{seller_id}/prepaid-cards" : {
      "get" : {
        "tags" : [ "Manager" ],
        "summary" : "Lista de cartões pré-pagos de um estabelecimento",
        "description" : "A listagem é feita pelo estabelecimento, trazendo todos os cartoes associados a ele",
        "operationId" : "get_all_cards_by_seller",
        "parameters" : [ {
          "name" : "marketplace_id",
          "in" : "path",
          "description" : "ID do marketplace para escopo dos cartões",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "seller_id",
          "in" : "path",
          "description" : "ID do estabelecimento",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "Listagem efetuada com sucesso",
            "schema" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/definitions/Card"
              }
            }
          },
          "400" : {
            "description" : "ID informado é inválido"
          },
          "401" : {
            "description" : "Solicitação não autorizada"
          },
          "404" : {
            "description" : "Estabelecimento não encontrado"
          }
        }
      }
    },
    "/marketplaces/{marketplace_id}/sellers/{seller_id}/prepaid-cards/{card_id}/activate" : {
      "put" : {
        "tags" : [ "Manager" ],
        "summary" : "Habilita um cartão pré-pago",
        "description" : "É possível Habilitar um cartão pré-pago. No processo de ativação do cartão uma URL será informada para redirecionamento para a operadora.",
        "operationId" : "activate_card",
        "parameters" : [ {
          "name" : "marketplace_id",
          "in" : "path",
          "description" : "ID do marketplace para escopo dos cartões",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "seller_id",
          "in" : "path",
          "description" : "ID do estabelecimento",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "card_id",
          "in" : "path",
          "description" : "ID do cartão pré-pago",
          "required" : true,
          "type" : "integer",
          "format" : "int64"
        } ],
        "responses" : {
          "200" : {
            "description" : "Cartão ativado com sucesso!",
            "schema" : {
              "$ref" : "#/definitions/Card"
            }
          },
          "400" : {
            "description" : "ID do cartão inválido inválido"
          },
          "401" : {
            "description" : "Solicitação não autorizada"
          }
        }
      }
    },
    "/marketplaces/{marketplace_id}/sellers/{seller_id}/prepaid-cards/{card_id}/block" : {
      "put" : {
        "tags" : [ "Manager" ],
        "summary" : "Bloqueia um cartão pré-pago",
        "description" : "É possível bloquear um cartão pré-pago.",
        "operationId" : "block_card",
        "parameters" : [ {
          "name" : "marketplace_id",
          "in" : "path",
          "description" : "ID do marketplace para escopo dos cartões",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "seller_id",
          "in" : "path",
          "description" : "ID do estabelecimento",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "card_id",
          "in" : "path",
          "description" : "ID do cartão pré-pago",
          "required" : true,
          "type" : "integer",
          "format" : "int64"
        } ],
        "responses" : {
          "200" : {
            "description" : "Bloqueio efetuado com sucesso!",
            "schema" : {
              "$ref" : "#/definitions/Card"
            }
          },
          "400" : {
            "description" : "ID do cartão inválido inválido"
          },
          "401" : {
            "description" : "Solicitação não autorizada"
          }
        }
      }
    },
    "/marketplaces/{marketplace_id}/sellers/{seller_id}/prepaid-cards/{card_id}/lock" : {
      "put" : {
        "tags" : [ "Manager" ],
        "summary" : "Bloqueia um cartão pré-pago temporariamente",
        "description" : "É possível bloquear um cartão pré-pago de forma temporária.",
        "operationId" : "lock_card",
        "parameters" : [ {
          "name" : "marketplace_id",
          "in" : "path",
          "description" : "ID do marketplace para escopo dos cartões",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "seller_id",
          "in" : "path",
          "description" : "ID do estabelecimento",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "card_id",
          "in" : "path",
          "description" : "ID do cartão pré-pago",
          "required" : true,
          "type" : "integer",
          "format" : "int64"
        } ],
        "responses" : {
          "200" : {
            "description" : "Bloqueio efetuado com sucesso!",
            "schema" : {
              "$ref" : "#/definitions/Card"
            }
          },
          "400" : {
            "description" : "ID do cartão inválido inválido"
          },
          "401" : {
            "description" : "Solicitação não autorizada"
          }
        }
      }
    },
    "/marketplaces/{marketplace_id}/sellers/{seller_id}/prepaid-cards/{card_id}/unlock" : {
      "put" : {
        "tags" : [ "Manager" ],
        "summary" : "Desbloqueia um cartão pré-pago",
        "description" : "É possível desbloquear um cartão pré-pago.",
        "operationId" : "unlock_card",
        "parameters" : [ {
          "name" : "marketplace_id",
          "in" : "path",
          "description" : "ID do marketplace para escopo dos cartões",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "seller_id",
          "in" : "path",
          "description" : "ID do estabelecimento",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "card_id",
          "in" : "path",
          "description" : "ID do cartão pré-pago",
          "required" : true,
          "type" : "integer",
          "format" : "int64"
        } ],
        "responses" : {
          "200" : {
            "description" : "Bloqueio efetuado com sucesso!",
            "schema" : {
              "$ref" : "#/definitions/Card"
            }
          },
          "400" : {
            "description" : "ID do cartão inválido inválido"
          },
          "401" : {
            "description" : "Solicitação não autorizada"
          }
        }
      }
    },
    "/healthcheck" : {
      "get" : {
        "summary" : "Checagem da aplicação",
        "description" : "Usado para ver se a aplicação está online",
        "operationId" : "healthcheck",
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "Aplicação online."
          },
          "404" : {
            "description" : "Problema na aplicação"
          }
        }
      }
    }
  },
  "securityDefinitions" : {
    "ApiKeyAuth" : {
      "type" : "apiKey",
      "name" : "Authorization",
      "in" : "header"
    }
  },
  "definitions" : {
    "CardAssociation" : {
      "type" : "object",
      "properties" : {
        "card_id" : {
          "type" : "integer",
          "description" : "ID do cartão exibido na parte de trás do cartão"
        },
        "seller_document" : {
          "type" : "string",
          "description" : "CPF ou CNPJ do solicitante."
        },
        "mothers_name" : {
          "type" : "string",
          "description" : "Nome da mãe do usuário do cartão"
        },
        "resource" : {
          "type" : "string"
        },
        "uri" : {
          "type" : "string"
        }
      },
      "example" : {
        "seller_document" : 6,
        "resource" : "resource",
        "uri" : "uri",
        "card_id" : 0
      }
    },
    "Card" : {
      "type" : "object",
      "properties" : {
        "bank_account_id" : {
          "type" : "string",
          "description" : "Bank account associado ao cartão"
        },
        "card_id" : {
          "type" : "integer",
          "description" : "Número do cartão exibido no verso do cartão"
        },
        "card_mask_number" : {
          "type" : "string",
          "description" : "Os números do cartão de forma máscarada"
        },
        "card_name" : {
          "type" : "string",
          "description" : "Nome do Holder no cartão"
        },
        "balance" : {
          "type" : "string",
          "description" : "Saldo do cartão"
        },
        "status" : {
          "type" : "string",
          "description" : "Status do cartão pré-pago",
          "enum" : [ "pending", "active", "blocked" ]
        },
        "resource" : {
          "type" : "string"
        },
        "uri" : {
          "type" : "string"
        }
      },
      "example" : {
        "bank_account_id" : "bankaccountid",
        "balance" : "balance",
        "resource" : "resource",
        "card_name" : "card_name",
        "uri" : "uri",
        "card_id" : 123456,
        "card_mask_number" : "card_mask_number",
        "status" : "pending"
      }
    },
    "CardDetail" : {
      "type" : "object",
      "properties" : {
        "card_id" : {
          "type" : "integer",
          "description" : "Número do cartão exibido no verso do cartão"
        },
        "card_mask_number" : {
          "type" : "string",
          "description" : "Os números do cartão de forma máscarada"
        },
        "holder_name" : {
          "type" : "string",
          "description" : "Nome do Holder no cartão"
        },
        "document" : {
          "type" : "object",
          "description" : "Documento do portador",
          "properties" : { }
        },
        "valid_date" : {
          "type" : "string",
          "description" : "Data de validade do cartão"
        },
        "last_4_digit" : {
          "type" : "string",
          "description" : "Ultimos 4 digitos do cartão"
        },
        "status" : {
          "type" : "string",
          "description" : "Status do cartão pré-pago",
          "enum" : [ "inactive", "active", "blocked" ]
        },
        "resource" : {
          "type" : "string"
        },
        "uri" : {
          "type" : "string"
        }
      },
      "example" : {
        "valid_date" : "valid_date",
        "last_4_digit" : "last_4_digit",
        "resource" : "resource",
        "document" : "{}",
        "uri" : "uri",
        "card_id" : 0,
        "card_mask_number" : "card_mask_number",
        "holder_name" : "holder_name",
        "status" : "inactive"
      }
    },
    "Cards" : {
      "type" : "object",
      "properties" : {
        "items" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/Card"
          }
        },
        "resource" : {
          "type" : "string"
        },
        "uri" : {
          "type" : "string"
        },
        "limit" : {
          "type" : "integer"
        },
        "offset" : {
          "type" : "integer"
        },
        "has_more" : {
          "type" : "boolean"
        },
        "query_count" : {
          "type" : "integer"
        },
        "total" : {
          "type" : "integer"
        }
      },
      "example" : {
        "card_number_first" : 1,
        "resource" : "resource",
        "id" : 0,
        "card_number_last" : 5,
        "uri" : "uri",
        "card_id" : 6,
        "establishment_name" : "establishment_name",
        "status" : "pending"
      }
    }
  }
}
